[package]
name = "bunner_qs"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
indexmap = "2.2"
encoding_rs = "0.8"
percent-encoding = "2.3"
once_cell = "1.19"
thiserror = "1.0"

[dev-dependencies]
serde_json = "1.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
